/* export const asyncCatch = (err, req, res, next) => {
  return (fn) => {
    fn(req, res, next).catch((err) => next(err));
  };
};
 */
